version: "3.7"
services:
  app:
    build:
      args:
        user: ${USER} # Sử dụng biến môi trường hiện tại cho user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shopgiay
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD: 
      MYSQL_USER: 
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel_network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
